
UPDATE twitter_user
SET state = 
CASE
WHEN state = 'AK' THEN 'Alaska'
WHEN state = 'AL' THEN 'Alabama'
WHEN state = 'AR' THEN 'Arkansas'
WHEN state = 'AS' THEN 'American Samoa'
WHEN state = 'AZ' THEN 'Arizona'
WHEN state = 'CA' THEN 'California '
WHEN state = 'CO' THEN 'Colorado '
WHEN state = 'CT' THEN 'Conecticut'
WHEN state = 'DC' THEN 'District of Columbia'
WHEN state = 'DE' THEN 'Delaware'
WHEN state = 'FL' THEN 'Florida'
WHEN state = 'FM' THEN 'Federated States of Micronesia'
WHEN state = 'GA' THEN 'Georgia'
WHEN state = 'GU' THEN 'Guam'
WHEN state = 'HI' THEN 'Hawaii'
WHEN state = 'IA' THEN 'Iowa'
WHEN state = 'ID' THEN 'Idaho'
WHEN state = 'IL' THEN 'Illinois'
WHEN state = 'IN' THEN 'Indiana'
WHEN state = 'KS' THEN 'Kansas'
WHEN state = 'KY' THEN 'Kentucky'
WHEN state = 'LA' THEN 'Louisiana'
WHEN state = 'MA' THEN 'Massachusetts'
WHEN state = 'MD' THEN 'Maryland'
WHEN state = 'ME' THEN 'Maine'
WHEN state = 'MH' THEN 'Marshall Islands'
WHEN state = 'MI' THEN 'Michigan'
WHEN state = 'MN' THEN 'Minnesota'
WHEN state = 'MO' THEN 'Missouri'
WHEN state = 'MP' THEN 'Northern Mariana Islands'
WHEN state = 'MS' THEN 'Mississippi'
WHEN state = 'MT' THEN 'Montana'
WHEN state = 'NC' THEN 'North Carolina'
WHEN state = 'ND' THEN 'North Dakota'
WHEN state = 'NE' THEN 'Nebraska'
WHEN state = 'NH' THEN 'New Hampshire'
WHEN state = 'NJ' THEN 'New Jersey'
WHEN state = 'NM' THEN 'New Mexico'
WHEN state = 'NV' THEN 'Nevada'
WHEN state = 'NY' THEN 'New York'
WHEN state = 'OH' THEN 'Ohio'
WHEN state = 'OK' THEN 'Oklohoma'
WHEN state = 'OR' THEN 'Oregon'
WHEN state = 'PA' THEN 'Pennsylvania'
WHEN state = 'PR' THEN 'Puerto Rico'
WHEN state = 'RI' THEN 'Rhode Island'
WHEN state = 'SC' THEN 'South Carolina'
WHEN state = 'SD' THEN 'South Dakota'
WHEN state = 'TN' THEN 'Tennessee'
WHEN state = 'TX' THEN 'Texas'
WHEN state = 'UT' THEN 'Utah'
WHEN state = 'VA' THEN 'Virginia '
WHEN state = 'VI' THEN 'Virgin Islands'
WHEN state = 'VT' THEN 'Vermont'
WHEN state = 'WA' THEN 'Washington'
WHEN state = 'WI' THEN 'Wisconsin'
WHEN state = 'WV' THEN 'West Virginia'
WHEN state = 'WY' THEN 'Wyoming'
WHEN state = 'na' THEN 'na'
ELSE state END;

DROP TRIGGER IF EXISTS state_check;

DELIMITER ;;
CREATE TRIGGER state_check BEFORE INSERT ON twitter_user FOR EACH ROW BEGIN
    UPDATE twitter_user
    SET state = 
	CASE
	WHEN state = 'AK' THEN 'Alaska'
	WHEN state = 'AL' THEN 'Alabama'
	WHEN state = 'AR' THEN 'Arkansas'
	WHEN state = 'AS' THEN 'American Samoa'
	WHEN state = 'AZ' THEN 'Arizona'
	WHEN state = 'CA' THEN 'California '
	WHEN state = 'CO' THEN 'Colorado '
	WHEN state = 'CT' THEN 'Conecticut'
	WHEN state = 'DC' THEN 'District of Columbia'
	WHEN state = 'DE' THEN 'Delaware'
	WHEN state = 'FL' THEN 'Florida'
	WHEN state = 'FM' THEN 'Federated States of Micronesia'
	WHEN state = 'GA' THEN 'Georgia'
	WHEN state = 'GU' THEN 'Guam'
	WHEN state = 'HI' THEN 'Hawaii'
	WHEN state = 'IA' THEN 'Iowa'
	WHEN state = 'ID' THEN 'Idaho'
	WHEN state = 'IL' THEN 'Illinois'
	WHEN state = 'IN' THEN 'Indiana'
	WHEN state = 'KS' THEN 'Kansas'
	WHEN state = 'KY' THEN 'Kentucky'
	WHEN state = 'LA' THEN 'Louisiana'
	WHEN state = 'MA' THEN 'Massachusetts'
	WHEN state = 'MD' THEN 'Maryland'
	WHEN state = 'ME' THEN 'Maine'
	WHEN state = 'MH' THEN 'Marshall Islands'
	WHEN state = 'MI' THEN 'Michigan'
	WHEN state = 'MN' THEN 'Minnesota'
	WHEN state = 'MO' THEN 'Missouri'
	WHEN state = 'MP' THEN 'Northern Mariana Islands'
	WHEN state = 'MS' THEN 'Mississippi'
	WHEN state = 'MT' THEN 'Montana'
	WHEN state = 'NC' THEN 'North Carolina'
	WHEN state = 'ND' THEN 'North Dakota'
	WHEN state = 'NE' THEN 'Nebraska'
	WHEN state = 'NH' THEN 'New Hampshire'
	WHEN state = 'NJ' THEN 'New Jersey'
	WHEN state = 'NM' THEN 'New Mexico'
	WHEN state = 'NV' THEN 'Nevada'
	WHEN state = 'NY' THEN 'New York'
	WHEN state = 'OH' THEN 'Ohio'
	WHEN state = 'OK' THEN 'Oklohoma'
	WHEN state = 'OR' THEN 'Oregon'
	WHEN state = 'PA' THEN 'Pennsylvania'
	WHEN state = 'PR' THEN 'Puerto Rico'
	WHEN state = 'RI' THEN 'Rhode Island'
	WHEN state = 'SC' THEN 'South Carolina'
	WHEN state = 'SD' THEN 'South Dakota'
	WHEN state = 'TN' THEN 'Tennessee'
	WHEN state = 'TX' THEN 'Texas'
	WHEN state = 'UT' THEN 'Utah'
	WHEN state = 'VA' THEN 'Virginia '
	WHEN state = 'VI' THEN 'Virgin Islands'
	WHEN state = 'VT' THEN 'Vermont'
	WHEN state = 'WA' THEN 'Washington'
	WHEN state = 'WI' THEN 'Wisconsin'
	WHEN state = 'WV' THEN 'West Virginia'
	WHEN state = 'WY' THEN 'Wyoming'
	WHEN state = 'na' THEN 'na'
	ELSE state END;
  END;;
DELIMITER ;